"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config, Csv
import os
import re
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 1. Primeiro: Define o BASE_DIR (movido para o topo)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Segundo: Define a função que depende do BASE_DIR
def get_version_from_changelog():
    print(f"--- DEBUG VERSION: BASE_DIR é {BASE_DIR} ---")
    
    # Lista de tentativas de caminho
    paths = [
        os.path.join(BASE_DIR, 'CHANGELOG.md'),         # Tenta na raiz do app
        os.path.join(BASE_DIR, '..', 'CHANGELOG.md'),   # Tenta um nível acima (caso o app esteja numa subpasta)
        os.path.join(BASE_DIR, 'app', 'CHANGELOG.md'),  # Tenta numa subpasta app
    ]
    
    for changelog_path in paths:
        # Normaliza o caminho para evitar problemas com / ou \
        full_path = os.path.abspath(changelog_path)
        print(f"--- DEBUG VERSION: Tentando ler em: {full_path} ---")
        
        try:
            if os.path.exists(full_path):
                print("--- DEBUG VERSION: Arquivo ENCONTRADO! Lendo conteúdo... ---")
                with open(full_path, 'r', encoding='utf-8') as f:
                    for i, line in enumerate(f):
                        if i > 20: break 
                        print(f"--- DEBUG VERSION Linha {i}: {line.strip()} ---") # Mostra o que está lendo
                        
                        # Regex para capturar vX.X.X
                        match = re.search(r'Release v?(\d+\.\d+\.\d+)', line, re.IGNORECASE)
                        if match:
                            version = match.group(1)
                            print(f"--- DEBUG VERSION: SUCESSO! Versão extraída: {version} ---")
                            return version
            else:
                print("--- DEBUG VERSION: Arquivo não existe neste caminho. ---")
        except Exception as e:
            print(f"--- DEBUG VERSION: Erro ao ler arquivo: {e} ---")
            continue
            
    print("--- DEBUG VERSION: Falha total. Retornando 0.0.0 ---")
    return '0.0.0'

APP_VERSION = get_version_from_changelog()
# --------------------------------------------------------

# Google Maps API Key
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='chave_nao_configurada')

# Weather API Key
WEATHER_API_KEY = os.environ.get('WEATHER_API_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-chave-temporaria-fallback')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'# Adicione esta lógica para ler a variável de ambiente

# 1. ALLOWED_HOSTS (Blindado contra erros de formatação)
allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS')

if allowed_hosts_env:
    # Passo A: Troca qualquer espaço possível por vírgula
    # Passo B: Divide pela vírgula
    # Passo C: Remove espaços vazios e itens nulos
    ALLOWED_HOSTS = [
        host.strip() 
        for host in allowed_hosts_env.replace(' ', ',').split(',') 
        if host.strip()
    ]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# 2. CSRF (Origens Confiáveis)
# Adiciona https:// na frente de cada host válido
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS]

# Debug para garantir que agora ficou certo (pode remover depois)
print(f"--- DEBUG FINAL ALLOWED_HOSTS: {ALLOWED_HOSTS} ---")
print(f"--- DEBUG FINAL CSRF: {CSRF_TRUSTED_ORIGINS} ---")

# Application definition
INSTALLED_APPS = [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.export_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuração Dinâmica de Banco de Dados
# Se houver variáveis de ambiente (Docker), usa Postgres.
# Caso contrário (rodando local sem docker), usa SQLite como fallback.

if os.environ.get('SQL_DATABASE') and os.environ.get('SQL_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('SQL_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('SQL_DATABASE'),
            'USER': os.environ.get('SQL_USER'),
            'PASSWORD': os.environ.get('SQL_PASSWORD'),
            'HOST': os.environ.get('SQL_HOST'),
            'PORT': os.environ.get('SQL_PORT', '5432'),
        }
    }
else:
    # Fallback apenas para desenvolvimento local fora do Docker
    print("⚠️  AVISO: Usando SQLite local (Variáveis de ambiente do Postgres não encontradas)")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True # Ativa a localização de formatos

USE_TZ = True

# 3. Configurações Específicas de Formatação Numérica
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'
NUMBER_GROUPING = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Pasta onde o Gunicorn vai buscar

# Compressão e cache eficiente para produção
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração de Redirecionamento de Login/Logout
LOGIN_REDIRECT_URL = 'home'  # Redireciona para a view com name='home' após logar
LOGOUT_REDIRECT_URL = 'login' # Redireciona para a tela de login após sair
LOGIN_URL = 'login' # Caso o usuário tente acessar uma página restrita sem estar logado

# Configuração de Arquivos de Mídia (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
