# Generated by Django 5.2.9 on 2025-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)'), ('CLP', 'Peso Chileno (CLP)'), ('ARS', 'Peso Argentino (ARS)'), ('UYU', 'Peso Uruguaio (UYU)'), ('COP', 'Peso Colombiano (COP)'), ('PEN', 'Sol Peruano (PEN)'), ('CAD', 'Dólar Canadense (CAD)'), ('GBP', 'Libra Esterlina (GBP)'), ('CHF', 'Franco Suíço (CHF)'), ('AUD', 'Dólar Australiano (AUD)'), ('JPY', 'Iene Japonês (JPY)')], default='BRL', max_length=3),
        ),
    ]
