# Generated by Django 5.2.9 on 2025-12-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expense_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trip_files/', verbose_name='Arquivo (PDF/Img)')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição (Opcional)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.tripitem')),
            ],
        ),
    ]
